### PR TITLE
[FIX] Fixes commented by @pablocm-aserti

### PR DESCRIPTION
**Pull request by antespi**

### CODE REVIEW

**Comment by antespi** [comment]
Fixes from @pablocm-aserti comments:

- Taxes list is readonly
- _install_tax_detail won't execute on updating addon, only on installing

**Comment by antespi** [comment]
Please @ah-taktik, review and merge if you are agree, for finish merging at OCA PR

**Comment by pablocm-aserti** [comment]
Thanks!
LGTM :+1:

**Comment by pablocm-aserti** [comment]
Sorry, I overlooked it too, but as the ci/runbot check says, it is missing the ACL rules.
Would you mind adding them please?
Thanks!

**Comment by antespi** [comment]
Thanks @pablocm-aserti, you're right. I've just add ACL rules

**Comment by pablocm-aserti** [comment]
Shouldn't the group_pos_manager have full rights too?
Removing its line will grant it 1,1,1,1 inherited from the user, but as of now, I think it is restricted to read only.

**Comment by antespi** [comment]
@pablocm-aserti, you're right, but I've copy&paste from rules assigned to model pos.order in official poiny_of_sale addon. Maybe they are wrong too?
I've changed in my last commit.

**Comment by ah-taktik** [comment]
It seems ok for me !
@antespi, @pablocm-aserti, Thank you.

**Pull request merged**
